lr: 0.0001
if_cuda: False
num_gpus: 0
train_batch: 32
val_batch: 32
test_batch: 32
data_filepath: '../data/pdf'
loss: 'CrossEntropy'
epochs: 500
seed: 2
log_dir: '../logs'
model_name: 'conv2d_robust'
num_workers: 8
normalization: 'sample'
input_noise: False
noise_scale: 0.0
dropout_rate: 0.5
precision: 32
